version: '3.3'
services:
 srclbd:
  build: ./srclbd
  ports:
   - "3307:3306"
  expose:
   - "3306"
  volumes:
   - ./srclbd/data:/var/lib/mysql
 eureka:
  build: ./Eureka
  ports:
   - "8761:8761"
  expose:
   - "8761"
 matriculas-ms:
  build: ./matriculas-ms
  ports:
   - "3333:3333"
  expose:
   - "3333"
  depends_on:
   - srclbd
   - eureka
  links:
   - srclbd
   - eureka
  environment:
   - DATABASE_HOST=srclbd
   - EUREKA_HOST=eureka



 
